{{- if lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "karpenter.sh" "NodeOverlay" -}}
apiVersion: karpenter.sh/v1alpha1
kind: NodeOverlay
metadata:
  name: tensor-fusion-overlay
spec:
  requirements: []
  capacity:
    tensor-fusion.ai/index_0: 36
    tensor-fusion.ai/index_1: 36
    tensor-fusion.ai/index_2: 36
    tensor-fusion.ai/index_3: 36
    tensor-fusion.ai/index_4: 36
    tensor-fusion.ai/index_5: 36
    tensor-fusion.ai/index_6: 36
    tensor-fusion.ai/index_7: 36
    tensor-fusion.ai/index_8: 36
    tensor-fusion.ai/index_9: 36
    tensor-fusion.ai/index_a: 36
    tensor-fusion.ai/index_b: 36
    tensor-fusion.ai/index_c: 36
    tensor-fusion.ai/index_d: 36
    tensor-fusion.ai/index_e: 36
    tensor-fusion.ai/index_f: 36
{{- end }}