{{- if lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "karpenter.sh" "NodeOverlay" -}}
apiVersion: karpenter.sh/v1alpha1
kind: NodeOverlay
metadata:
  name: tensor-fusion-overlay
spec:
  requirements: []
  capacity:
    tensor-fusion.ai/index_0: 28
    tensor-fusion.ai/index_1: 28
    tensor-fusion.ai/index_2: 28
    tensor-fusion.ai/index_3: 28
    tensor-fusion.ai/index_4: 28
    tensor-fusion.ai/index_5: 28
    tensor-fusion.ai/index_6: 28
    tensor-fusion.ai/index_7: 28
    tensor-fusion.ai/index_8: 28
    tensor-fusion.ai/index_9: 28
    tensor-fusion.ai/index_a: 28
    tensor-fusion.ai/index_b: 28
    tensor-fusion.ai/index_c: 28
    tensor-fusion.ai/index_d: 28
    tensor-fusion.ai/index_e: 28
    tensor-fusion.ai/index_f: 28
{{- end }}